---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test_api
  pull: if-not-exists
  image: docker/compose:alpine-1.25.5
  environment:
    DOCKER_HOST: tcp://127.0.0.1:2375
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! "$(docker stats --no-stream)" ]; do n=$(( n + 1 )); sleep 1; done
  - apk add bash curl
  - ./bin/test.sh
  when:
    event:
    - push

- name: build-clamav
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - cd clamav
    - /usr/local/bin/wait
    - docker build --no-cache -t clamav:$${DRONE_COMMIT_SHA} .

- name: build-clamav-http
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - cd clamav-http
    - /usr/local/bin/wait
    - docker build --no-cache -t clamav-http:$${DRONE_COMMIT_SHA} .

- name: build-clamav-mirror
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
    - cd clamav-mirror
    - /usr/local/bin/wait
    - docker build --no-cache -t clamav-mirror:$${DRONE_COMMIT_SHA} .

- name: scan-clamav-http
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: clamav-http:${DRONE_COMMIT_SHA}
    IGNORE_UNFIXED: "true"
  when:
    event:
    - pull_request
    - push

- name: scan-clamav
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: clamav:${DRONE_COMMIT_SHA}
    IGNORE_UNFIXED: "true"
  when:
    event:
    - pull_request
    - push

- name: scan-clamav-mirror
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: clamav-mirror:${DRONE_COMMIT_SHA}
    IGNORE_UNFIXED: "true"
  when:
    event:
    - pull_request
    - push

- name: tagged_clamav_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/acp-clamav:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/acp-clamav:$${DRONE_TAG}
  - docker push quay.io/ukhomeofficedigital/acp-clamav:$${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME: ukhomeofficedigital+acp_clamav
  when:
    event:
    - tag

- name: tagged_clamav_http_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/acp-clamav-http:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/acp-clamav-http:$${DRONE_TAG}
  - docker push quay.io/ukhomeofficedigital/acp-clamav-http:$${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME: ukhomeofficedigital+acp_clamav
  when:
    event:
    - tag

- name: tagged_clamav_mirror_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/acp-clamav-mirror:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/acp-clamav-mirror:$${DRONE_TAG}
  - docker push quay.io/ukhomeofficedigital/acp-clamav-mirror:$${DRONE_TAG}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME: ukhomeofficedigital+acp_clamav
  when:
    event:
    - tag

# Explanation: new version must be explicitly tagged. Also, latest tag is removed.
# Several tenants are using latest tag, therefore it is removed to eliminate a risk of
# accidental pull of new image. To use a new version, select explicit version number in
# the Kubernetes manifest. Thank you.
- name: all_images_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/acp-clamav:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/acp-clamav:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/acp-clamav:$${DRONE_COMMIT_SHA}
  - docker tag quay.io/ukhomeofficedigital/acp-clamav-http:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/acp-clamav-http:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/acp-clamav-http:$${DRONE_COMMIT_SHA}
  - docker tag quay.io/ukhomeofficedigital/acp-clamav-mirror:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/acp-clamav-mirror:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/acp-clamav-mirror:$${DRONE_COMMIT_SHA}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME: ukhomeofficedigital+acp_clamav
  when:
    branch:
    - master
    event:
    - push

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
