---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Blob
  pull: always
  image: alpine:3.23.4
  commands:
  - echo "blob"
  when:
    event:
    - push
    - pull_request

